### ISSUE TITLE
缺少cat_diff的模块

### ISSUE THREAD

**Issue by sqf041110** [udrs/diffusion-framework-for-CD-#4]
缺少cat_diff的模块
<img width="710" alt="image" src="https://github.com/udrs/GCD/assets/174311089/896cd4ab-5c05-4259-b91d-beabfdad8621">

**Comment by udrs** [comment]
please refrence the readme and complete your requirement. 
I have not worked for the lab anymore. I dont have any time to maintain this project cause I worked in industy.
Thank you for your patience and understanding.
